Update requirement on pyfakefs to >=3.4
This resolves a stack trace that occurs when using pyfakefs 3.3 or
earlier because we're using a method that only landed after 3.4:

   AttributeError: 'FakeFilesystem' object has no attribute 'create_file'

Change-Id: I07eee437313e9f701497cecaae4029952417a6e9