tests: pin factory-boy to <3.0
factory-boy just released a new 3.0 (and 3.0.1) version and it breaks
unit tests:
    AttributeError: module 'factory' has no attribute 'DjangoModelFactory'

Pin to <3.0 which is currently 2.12.0 while we figure it out.

Related: https://github.com/ansible-community/ara/issues/155
Change-Id: Id987e126a05cf084e6c9ed18884dad11c81d1203