Import pbr.version instead of pbr when retrieving version
It seems that under some circumstances, "pbr.version" can't be imported
and returns an error:

    "version": pbr.version.VersionInfo("ara").release_string(),
    AttributeError: module 'pbr' has no attribute 'version'

Change-Id: Ia04dcb49c18c45f1d235ae1158780a060e4053d8